# Generated by Django 4.2.23 on 2026-09-09 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import drawing_library.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee_management', '0005_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineeringDrawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Customer Name')),
                ('enquiry_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Enquiry Number')),
                ('po_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='PO Number')),
                ('pid_reference', models.CharField(max_length=150, verbose_name='P&ID Reference')),
                ('drawing_name', models.CharField(max_length=255, verbose_name='Drawing Name')),
                ('base_drawing_number', models.CharField(max_length=100, unique=True, verbose_name='Base Drawing Number')),
                ('active_revision_number', models.CharField(default='0', max_length=50, verbose_name='Active Revision Number')),
                ('drafter_name', models.CharField(max_length=150, verbose_name='Drafter Name')),
                ('format', models.CharField(choices=[('HAND_SKETCH', 'Hand Sketch'), ('ZWCAD', 'ZWCAD'), ('SOLIDWORKS', 'SolidWorks'), ('AUTOCAD', 'AutoCAD'), ('OTHER', 'Other')], default='ZWCAD', max_length=50, verbose_name='Format')),
                ('watermark_company', models.CharField(choices=[('PT FLOW FORCE INDONESIA', 'PT FLOW FORCE INDONESIA'), ('PT FLOW FORCE ENGINEERING', 'PT FLOW FORCE ENGINEERING')], default='PT FLOW FORCE INDONESIA', max_length=100, verbose_name='Watermark Company')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description / Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_drawings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Engineering Drawing',
                'verbose_name_plural': 'Engineering Drawings',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DrawingRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.CharField(max_length=50, verbose_name='Revision #')),
                ('stage_change_description', models.TextField(verbose_name='Stage Change Description')),
                ('native_file', models.FileField(blank=True, null=True, upload_to=drawing_library.models.drawing_native_upload_path, verbose_name='Native File Attachment')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=drawing_library.models.drawing_pdf_upload_path, verbose_name='Exported PDF File')),
                ('drafter_name', models.CharField(max_length=150, verbose_name='Drafter Name')),
                ('revision_date', models.DateField(default=django.utils.timezone.now, verbose_name='Revision Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drawing_revisions', to=settings.AUTH_USER_MODEL)),
                ('drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='drawing_library.engineeringdrawing')),
            ],
            options={
                'verbose_name': 'Drawing Revision',
                'verbose_name_plural': 'Drawing Revisions',
                'ordering': ['-revision_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DrawingAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('VIEW', 'View Only'), ('EDIT', 'Edit & Upload Revisions')], default='VIEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drawing_accesses', to='employee_management.department')),
                ('drawing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='drawing_library.engineeringdrawing')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_drawing_accesses', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drawing_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Drawing Access Permission',
                'verbose_name_plural': 'Drawing Access Permissions',
            },
        ),
    ]
