# Generated by Django 4.2.23 on 2026-09-09 05:40

from django.db import migrations, models
import drawing_library.models


class Migration(migrations.Migration):

    dependencies = [
        ('drawing_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawingrevision',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, storage=drawing_library.models.OverwriteStorage(), upload_to=drawing_library.models.drawing_pdf_upload_path, verbose_name='Exported PDF File'),
        ),
    ]
