# Generated by Django 4.2.23 on 2026-09-09 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0005_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drawing_library', '0002_alter_drawingrevision_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawingaccess',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drawing_accesses', to='employee_management.department'),
        ),
        migrations.CreateModel(
            name='DrawingActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawing_number', models.CharField(blank=True, max_length=100, null=True)),
                ('action', models.CharField(choices=[('VIEW_DRAWING', 'Viewed Drawing'), ('VIEW_PDF', 'Previewed Watermarked PDF'), ('DOWNLOAD_PDF', 'Downloaded Watermarked PDF'), ('DOWNLOAD_NATIVE', 'Downloaded Native CAD File'), ('CREATE_DRAWING', 'Created Drawing Project'), ('UPDATE_DRAWING', 'Updated Drawing Metadata'), ('DELETE_DRAWING', 'Deleted Drawing Project'), ('UPLOAD_REVISION', 'Uploaded New Revision'), ('DELETE_REVISION', 'Deleted Revision'), ('GRANT_ACCESS', 'Granted Access Clearance'), ('REVOKE_ACCESS', 'Revoked Access Clearance')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drawing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='drawing_library.engineeringdrawing')),
                ('revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='drawing_library.drawingrevision')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drawing_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Drawing Activity Log',
                'verbose_name_plural': 'Drawing Activity Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
