# Generated by Django 4.2.23 on 2026-09-09 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drawing_library', '0003_alter_drawingaccess_department_drawingactivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawingrevision',
            name='original_native_filename',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Original Native CAD Filename'),
        ),
        migrations.AddField(
            model_name='drawingrevision',
            name='original_pdf_filename',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Original PDF Filename'),
        ),
        migrations.AddField(
            model_name='engineeringdrawing',
            name='drawing_type',
            field=models.CharField(choices=[('MASTER', 'Level 1: Master / Parent Drawing'), ('SUB_ASSEMBLY', 'Level 2: Sub-Assembly (Child)'), ('DETAIL_PART', 'Level 3: Detail Part (Grandchild)')], default='MASTER', max_length=20, verbose_name='Drawing Type / Level'),
        ),
        migrations.AddField(
            model_name='engineeringdrawing',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='drawing_library.engineeringdrawing', verbose_name='Parent Drawing'),
        ),
        migrations.AddField(
            model_name='engineeringdrawing',
            name='project_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Project Name'),
        ),
    ]
