# Generated by Django 4.2.23 on 2026-09-09 11:56

from django.db import migrations, models
import drawing_library.models


class Migration(migrations.Migration):

    dependencies = [
        ('drawing_library', '0004_drawingrevision_original_native_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawingrevision',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=drawing_library.models.drawing_pdf_upload_path, verbose_name='Exported PDF File'),
        ),
    ]
