# Generated by Django 4.2.23 on 2026-09-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawing_library', '0005_alter_drawingrevision_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineeringdrawing',
            name='pid_reference',
            field=models.CharField(max_length=150, verbose_name='PID Reference'),
        ),
    ]
