# Generated by Django 4.2.23 on 2026-09-15 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawing_library', '0006_alter_engineeringdrawing_pid_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawingaccess',
            name='access_level',
            field=models.CharField(choices=[('VIEW', 'View & Download Only'), ('EDIT', 'Full Access (Create, Edit, Upload & Download)')], default='VIEW', max_length=20),
        ),
    ]
