# Generated by Django 4.2.23 on 2026-06-12 08:32

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0004_remove_employeeuser_is_approved_employeeuser_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedEmployee',
            fields=[
            ],
            options={
                'verbose_name': 'Managed Employee',
                'verbose_name_plural': 'Managed Employees',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth_app.employeeuser',),
        ),
    ]
