# Generated by Django 4.2.23 on 2026-06-16 07:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfilePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile_pictures/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_current', models.BooleanField(default=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_picture', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeLoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_at', models.DateTimeField(auto_now_add=True)),
                ('logout_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-login_at'],
                'indexes': [models.Index(fields=['employee', '-login_at'], name='employee_ma_employe_b6ca7d_idx'), models.Index(fields=['is_active'], name='employee_ma_is_acti_7a7bac_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeApprovalQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval_queue', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_approvals', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['-submitted_at'], name='employee_ma_submitt_6bf0db_idx'), models.Index(fields=['is_approved'], name='employee_ma_is_appr_db8288_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('CREATE', 'Employee Created'), ('UPDATE', 'Employee Updated'), ('DELETE', 'Employee Deleted'), ('ACTIVATE', 'Account Activated'), ('DEACTIVATE', 'Account Deactivated'), ('APPROVE', 'Employee Approved'), ('REJECT', 'Employee Rejected'), ('ROLE_CHANGE', 'Role Changed'), ('DEPARTMENT_CHANGE', 'Department Changed'), ('PASSWORD_RESET', 'Password Reset'), ('STATUS_CHANGE', 'Status Changed'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('EXPORT', 'Data Exported'), ('BULK_ACTION', 'Bulk Action')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='JSON field storing before/after values for updates')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', '-created_at'], name='employee_ma_employe_9539c9_idx'), models.Index(fields=['activity_type', '-created_at'], name='employee_ma_activit_46374e_idx'), models.Index(fields=['performed_by', '-created_at'], name='employee_ma_perform_3065fd_idx')],
            },
        ),
    ]
