# Generated by Django 4.2.23 on 2026-06-16 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee_management', '0002_employeeprofilepicture_employeeloginhistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Department name (e.g., Engineering, Sales, HR)', max_length=100, unique=True)),
                ('slug', models.SlugField(editable=False, help_text='URL-friendly identifier', unique=True)),
                ('description', models.TextField(blank=True, help_text='Department description and responsibilities')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive departments are hidden from selection')),
                ('color', models.CharField(default='#1F2937', help_text='Hex color for UI display (e.g., #FF5733)', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('head', models.ForeignKey(blank=True, help_text='Department head/manager', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_headed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'name'], name='employee_ma_is_acti_f9304e_idx'), models.Index(fields=['slug'], name='employee_ma_slug_f30bc0_idx')],
            },
        ),
    ]
