# Generated by Django 4.2.23 on 2026-06-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_passwordresetotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeuser',
            name='employee_id',
        ),
        migrations.AddField(
            model_name='employeeuser',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
