# Generated by Django 4.2.23 on 2026-06-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_remove_employeeuser_employee_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeuser',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='employeeuser',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
