# Generated by Django 4.2.23 on 2026-06-16 08:46

from django.db import migrations, models
import django.db.models.deletion


def create_departments(apps, schema_editor):
    """
    Create Department objects from existing department strings
    """
    Department = apps.get_model('employee_management', 'Department')
    EmployeeUser = apps.get_model('auth_app', 'EmployeeUser')
    
    # Get all unique non-empty department values
    unique_departments = set()
    for emp in EmployeeUser.objects.all():
        if emp.department and emp.department.strip():
            unique_departments.add(emp.department.strip())
    
    # Create Department objects
    for dept_name in unique_departments:
        Department.objects.get_or_create(name=dept_name)
    
    # Create default departments
    defaults = ['Operations', 'Engineering', 'Procurement', 'Sales', 'HR', 'Finance']
    for dept_name in defaults:
        Department.objects.get_or_create(name=dept_name)


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0004_migrate_departments'),
        ('auth_app', '0004_remove_employeeuser_is_approved_employeeuser_status'),
    ]

    operations = [
        migrations.RunPython(create_departments, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='employeeuser',
            name='department',
        ),
        migrations.AddField(
            model_name='employeeuser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employee_management.department'),
        ),
    ]
