# Generated by Django 4.2.23 on 2026-06-19 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee_management', '0005_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_new_tables', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_tables', to='employee_management.department')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_new_rows', to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(db_column='table_fk', on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='tables.table')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data_type', models.CharField(choices=[('TEXT', 'Text'), ('NUMBER', 'Number'), ('DATE', 'Date'), ('DATETIME', 'Datetime'), ('CHECKBOX', 'Checkbox'), ('DROPDOWN', 'Dropdown'), ('USER', 'Employee/User')], default='TEXT', max_length=50)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('is_system_column', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('table', models.ForeignKey(db_column='table_fk', on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='tables.table')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TableAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('VIEW', 'View Only'), ('EDIT', 'Edit cells'), ('ADMIN', 'Full Admin')], default='VIEW', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_accesses', to='employee_management.department')),
                ('table', models.ForeignKey(db_column='table_fk', on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='tables.table')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('table', 'user'), ('table', 'department')},
            },
        ),
        migrations.CreateModel(
            name='ColumnAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('HIDDEN', 'Hidden'), ('READ_ONLY', 'Read Only'), ('EDITABLE', 'Editable')], default='EDITABLE', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('column', models.ForeignKey(db_column='column_fk', on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='tables.column')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('column', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CellValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('column', models.ForeignKey(db_column='column_fk', on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='tables.column')),
                ('row', models.ForeignKey(db_column='row_fk', on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='tables.row')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_cells', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('row', 'column')},
            },
        ),
    ]
