# Generated by Django 4.2.23 on 2026-06-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='options',
            field=models.TextField(blank=True, help_text='Comma-separated options for dropdown', null=True),
        ),
    ]
