# Generated by Django 4.2.23 on 2026-06-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_column_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='job_type',
            field=models.CharField(choices=[('SALES', 'Sales'), ('GENERAL', 'General')], default='GENERAL', max_length=50),
        ),
    ]
