# Generated by Django 4.2.23 on 2026-06-23 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_table_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='job_type',
            field=models.CharField(choices=[('SALES', 'Sales'), ('GENERAL', 'General'), ('ENGINEER', 'Engineer')], default='GENERAL', max_length=50),
        ),
    ]
