# Generated by Django 4.2.23 on 2026-06-30 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_alter_table_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='job_type',
            field=models.CharField(choices=[('SALES', 'Sales'), ('GENERAL', 'General'), ('ENGINEER', 'Engineer'), ('LIST_PID', 'List PID')], default='GENERAL', max_length=50),
        ),
    ]
