# Generated by Django 4.2.23 on 2026-07-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_alter_table_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='is_filterable',
            field=models.BooleanField(default=False),
        ),
    ]
