# Generated by Django 4.2.23 on 2026-07-03 10:04

from django.db import migrations


def update_list_pid_columns(apps, schema_editor):
    Column = apps.get_model('tables', 'Column')
    Column.objects.filter(table__job_type='LIST_PID').update(is_system_column=False)

def reverse_list_pid_columns(apps, schema_editor):
    Column = apps.get_model('tables', 'Column')
    Column.objects.filter(table__job_type='LIST_PID').update(is_system_column=True)

class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0006_column_is_filterable'),
    ]

    operations = [
        migrations.RunPython(update_list_pid_columns, reverse_list_pid_columns),
    ]
