# Generated by Django 4.2.23 on 2026-07-03 10:22

from django.db import migrations


def rename_list_pid_enquiry_column(apps, schema_editor):
    Column = apps.get_model('tables', 'Column')
    Column.objects.filter(table__job_type='LIST_PID', name='ENQUIRY_NO').update(name='ENQUIRY_NO/QUOTATION_NO')

def reverse_rename_list_pid_enquiry_column(apps, schema_editor):
    Column = apps.get_model('tables', 'Column')
    Column.objects.filter(table__job_type='LIST_PID', name='ENQUIRY_NO/QUOTATION_NO').update(name='ENQUIRY_NO')

class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0007_update_existing_list_pid_columns'),
    ]

    operations = [
        migrations.RunPython(rename_list_pid_enquiry_column, reverse_rename_list_pid_enquiry_column),
    ]
