# Generated by Django 4.2.23 on 2026-07-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0008_rename_enquiry_no_to_quotation_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
