# Generated by Django 4.2.23 on 2026-07-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0009_alter_row_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='job_type',
            field=models.CharField(choices=[('SALES', 'Sales'), ('GENERAL', 'General'), ('ENGINEER', 'Engineer'), ('LIST_PID', 'List PID'), ('PERSONAL', 'Personal')], default='GENERAL', max_length=50),
        ),
    ]
