# Generated by Django 4.2.23 on 2026-08-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0012_update_existing_logs_columns_and_overdue'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cellvalue',
            index=models.Index(fields=['column', 'row'], name='tables_cell_column__407ab4_idx'),
        ),
    ]
