# Generated by Django 4.2.23 on 2026-06-20 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emaillog',
            old_name='error_msg',
            new_name='error_message',
        ),
        migrations.AddField(
            model_name='emaillog',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='max_retries',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='alert_mail_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='initial_mail_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='last_escalation_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='last_escalation_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='email_type',
            field=models.CharField(choices=[('INITIAL_MAIL', 'Initial Assignment Mail'), ('ALERT_MAIL', 'Daily Alert Mail'), ('REVIEW_REQUEST_MAIL', 'Review Request Mail'), ('APPROVAL_STATUS_MAIL', 'Approval Status Mail'), ('OVERDUE_ESCALATION_MAIL', 'Overdue Escalation Mail')], max_length=50),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='task',
            field=models.ForeignKey(blank=True, db_column='task_fk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='tasks.task'),
        ),
    ]
