# Generated by Django 4.2.23 on 2026-06-26 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0003_rename_error_msg_emaillog_error_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_date', models.DateField(help_text='The date this follow-up was scheduled and conducted')),
                ('discussed_points', models.TextField(help_text='Detailed points of what was discussed')),
                ('next_follow_up_date', models.DateField(blank=True, help_text='The scheduled next follow-up date (if continuing)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_follow_ups', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(db_column='task_fk', on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='tasks.task')),
            ],
            options={
                'ordering': ['-follow_up_date', '-created_at'],
            },
        ),
    ]
