# Generated by Django 4.2.23 on 2026-06-12 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import task_tracker.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_tracker', '0004_add_aux_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackerrow',
            name='priority',
            field=models.CharField(choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH'), ('CRITICAL', 'CRITICAL')], default='MEDIUM', max_length=20),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='file',
            field=models.FileField(upload_to=task_tracker.models.attachment_upload_to),
        ),
        migrations.AlterField(
            model_name='trackerrow',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('ON_HOLD', 'ON_HOLD'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='TaskFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('query_params', models.JSONField(blank=True, default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_filters', to='task_tracker.tracker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_filters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
                'unique_together': {('user', 'tracker', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('PRIMARY', 'PRIMARY'), ('SECONDARY', 'SECONDARY'), ('WATCHER', 'WATCHER')], default='PRIMARY', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_assignment_actions', to=settings.AUTH_USER_MODEL)),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='task_tracker.trackerrow')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', 'id'],
                'unique_together': {('row', 'user', 'assignment_type')},
            },
        ),
    ]
