# Generated by Django 4.2.23 on 2026-06-16 08:46

from django.db import migrations, models
import django.db.models.deletion


def create_and_map_departments(apps, schema_editor):
    """
    Create Department objects from existing tracker departments
    and map tracker department_name to department_id
    """
    Department = apps.get_model('employee_management', 'Department')
    Tracker = apps.get_model('task_tracker', 'Tracker')
    
    # Get all unique department values from Tracker  
    dept_map = {}
    for tracker in Tracker.objects.all():
        if tracker.department and tracker.department.strip():
            dept_name = str(tracker.department).strip()
            if dept_name not in dept_map:
                dept, created = Department.objects.get_or_create(name=dept_name)
                dept_map[dept_name] = dept.id
    
    # Now we'll need to update trackers after the field is created
    # This will be handled by subsequent migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0004_migrate_departments'),
        ('task_tracker', '0005_trackerrow_priority_alter_taskattachment_file_and_more'),
    ]

    operations = [
        migrations.RunPython(create_and_map_departments, migrations.RunPython.noop),
        # First: Add the new FK field as nullable, keeping the old field
        migrations.AddField(
            model_name='tracker',
            name='department_fk',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='trackers_temp', to='employee_management.department'),
        ),
    ]

