# Generated by Django 4.2.23 on 2026-06-19 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee_management', '0005_team'),
        ('task_tracker', '0007_complete_department_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('SENT', 'SENT'), ('FAILED', 'FAILED')], default='SENT', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='tracker',
            options={'ordering': ['id']},
        ),
        migrations.AlterUniqueTogether(
            name='tracker',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tracker',
            name='shared_with_departments',
            field=models.ManyToManyField(blank=True, related_name='shared_trackers', to='employee_management.department'),
        ),
        migrations.AddField(
            model_name='tracker',
            name='shared_with_teams',
            field=models.ManyToManyField(blank=True, related_name='shared_trackers', to='employee_management.team'),
        ),
        migrations.AddField(
            model_name='tracker',
            name='shared_with_users',
            field=models.ManyToManyField(blank=True, related_name='shared_trackers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trackercolumn',
            name='choices',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='trackercolumn',
            name='column_type',
            field=models.CharField(default='TEXT', max_length=30),
        ),
        migrations.AddField(
            model_name='trackercolumn',
            name='default_value',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='trackercolumn',
            name='is_frozen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trackercolumn',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trackercolumn',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trackercolumn',
            name='is_read_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trackercolumn',
            name='permission_level',
            field=models.CharField(default='ALL_EDITABLE', max_length=30),
        ),
        migrations.AddField(
            model_name='trackercolumn',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trackercolumn',
            name='unique',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trackerrow',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department this tracker belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trackers', to='employee_management.department'),
        ),
    ]
